version: '3.5'
services:
  fpm:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/srv/www:rw
    environment:
      POSTGRESQL_HOST: postgres.svc.local
      RABBITMQ_HOST: rabbitmq.svc.local
    depends_on:
      - rabbitmq
      - postgres
    networks:
      local:
        aliases:
          - fpm.svc.local
  nginx:
    image: nginx
    volumes:
      - ./etc/nginx/conf:/etc/nginx/conf.d
      - ./etc/nginx/entrypoint.sh:/entrypoint.sh
    ports:
      - "8080:80"
    environment:
      NGINX_HOST: proxr.local
      NGINX_PORT: 80
      NGINX_FPM_URL: fpm.svc.local:9000
    command: /bin/bash /entrypoint.sh nginx -g 'daemon off;'
    depends_on:
      - fpm
    networks:
      local:
        aliases:
          - nginx.svc.local

  postgres:
    image:  postgres:10
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_USER: developer
      POSTGRES_DB: proxr
    networks:
      local:
        aliases:
          - postgres.svc.local

  rabbitmq:
    image: rabbitmq:3.7.2-management
#    ports:
#      - "15672:15672"
    networks:
      local:
        aliases:
          - rabbit.svc.local
networks:
  local:
    external:
      name: local