<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('PROXR Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header"></li>
                <li class="active">
                    <a href="<?php echo $this->url('home') ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Devices</span></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-diamond"></i> <span class="nav-label">Scripts</span></a>
                </li>
            </ul>
        </div>
    </nav>


    <div id="page-wrapper" class="gray-bg dashbard-1" style="min-height: 962px;">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">Bottom navbar</div>
            </nav>
        </div>
        <div class="row  border-bottom white-bg dashboard-header">
            <div class="col-sm-3">
                <div class="container"><?php echo $this->content; ?></div>
            </div>
        </div>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
