<?php
/**
 * @var \Doctrine\Common\Collections\ArrayCollection $devices
 * @var \Application\Entity\Device $device
 */

?>
<div class="row">
    <?php foreach($devices as $device) { ?>
        <?php
            $status = $device->getStatus()->getCode() === \Application\Entity\Status\Device::STATUS_ACTIVE ? 'label-primary' : 'label-danger';
        ?>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label <?php echo $status; ?> pull-right"><?php echo $device->getStatus()->getCode(); ?></span>
                <h5><?php echo $device->getName(); ?></h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">Scripts running: 0</h1>
                <div class="stat-percent font-bold text-success"><?php echo $device->getBanks()->count(); ?></div>
                <small>Total banks</small>
                <br clear="all" />
                <div class="btn-group">
                    <button data-toggle="dropdown" class="btn btn-default btn-xs dropdown-toggle" aria-expanded="false">Action <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('device/view', ['id' => $device->getId()]); ?>">Details</a></li>
                        <li><a href="#">Disable</a></li>
                        <li><a href="#">Show events</a></li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('event/device', ['deviceId' => $device->getId()]); ?>">Add activity</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <?php } ?>
</div>